spring:
  application:
    name: t1-java-demo
  datasource:
    url: "jdbc:postgresql://localhost:5432/t1_demo"
    username: "postgres"
    password: "0000"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    token: yfewyu7294bfj2h9uhbt5gty73uio32i4jhrbvfweigurh32e6789f90uvjnslilaoyegfwwf0001huebf384y5673894uh
    expiration: 86400000
  integration:

logging:
  level:
    ROOT: ${LOG_LEVEL:INFO}
    ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  scan-path: ru.t1.java.demo
  kafka:
    enabled: true
    server: localhost:29092
    consumer:
      group-id: t1-demo
      max.poll.records: 10
      session-timeout: 10000
      heartbeat.interval: 3000
    producer:
      enable: true
    topic:
      transaction: t1_demo_transactions
      transaction_result: t1_demo_transaction_result
    metricTopic: t1_demo_metrics
    listener:
      poll-timeout: 1000

metric:
  method-time-limit: -1
  logging:
    enabled: true

ru.t1.java.demo.cache:
  record-lifetime: 60000

black.list.checker:
  reject-threshold: 3

integration:
  url: http://localhost:8083/api/
  unblock-server-url: http://localhost:8084/api/unblock

transaction:
  max-rejected-count: 5

schema:
  enabled: true

scheduling:
  enabled: true
  tasks:
    client:
      period-ms: 3000
      batch-size: 3
    account:
      period-ms: 3000
      batch-size: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics







